##---
# Storage account that the MongoDB will use (The storage type), the type pd-ssd means that we will use SSD storage for the database
---
apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
##---
# Persistent Volume MongoDB will use, here an actual storage space will be reserved, I am choosing 20GigaByte for disk-space with read write permissions
# and using the previous defined type, and define the host path under /mnt/mdata
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-storage
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mdata"
##---
# Persistent Volume Claim with its configuration, this is the claim that will link specific deployment with specific storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
##---
# Deploying headless service, a network entity that describes the MongoDB service and on which port it will work on
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
##---
# Creating the deployment using an image from Docker hub and some database configuration, and linking the deployment with the storage claim to be able to access that storage
# choosing also the monut point where Mongo pods can access the storage
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
        environment: test
    spec:
      containers:
      - image: mongo
        name: mongo
        env:
          # Use secret in real usage
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: Pa$$w0rd
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim