apiVersion: v1
kind: Service
metadata:
  name: books
  labels: 
    app: books
spec:
  selector:
    app: books
  ports:
  - name: http
    port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
        version: v1
    spec:
      containers:
      - name: auth
        image: <docker image path>
        ports:
        - containerPort: 8000 
        env:
        - name: PORT
          value: "8000"